### ISSUE TITLE
Prepare Training Data and Train TF Model on ECUSTFD dataset

### ISSUE THREAD

**Issue by RobbieZhuang** [kallentu/chowdr#13]
- Prep data for putting into object detection (1 person)
- Training py (1 person)
- Testing py (with frozen graph and validation data) (1 person)
- Train model on 1 fold (1 person)

**Comment by Bimde** [comment]
Consider using https://www.tensorflow.org/tutorials/images/transfer_learning

**Comment by Bimde** [comment]
Now using: https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html
